// Code generated by MockGen. DO NOT EDIT.
// Source: internal/features/tasks/service/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/features/tasks/service/service.go -destination=internal/features/tasks/service/mocks/mock_service.go -package=tasks_service_mocks
//

// Package tasks_service_mocks is a generated GoMock package.
package tasks_service_mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/horizoonn/todoapp/internal/core/domain"
	tasks "github.com/horizoonn/todoapp/internal/features/tasks"
	gomock "go.uber.org/mock/gomock"
)

// MockTasksRepository is a mock of TasksRepository interface.
type MockTasksRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTasksRepositoryMockRecorder
	isgomock struct{}
}

// MockTasksRepositoryMockRecorder is the mock recorder for MockTasksRepository.
type MockTasksRepositoryMockRecorder struct {
	mock *MockTasksRepository
}

// NewMockTasksRepository creates a new mock instance.
func NewMockTasksRepository(ctrl *gomock.Controller) *MockTasksRepository {
	mock := &MockTasksRepository{ctrl: ctrl}
	mock.recorder = &MockTasksRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTasksRepository) EXPECT() *MockTasksRepositoryMockRecorder {
	return m.recorder
}

// DeleteTask mocks base method.
func (m *MockTasksRepository) DeleteTask(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTasksRepositoryMockRecorder) DeleteTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTasksRepository)(nil).DeleteTask), ctx, id)
}

// GetTask mocks base method.
func (m *MockTasksRepository) GetTask(ctx context.Context, id uuid.UUID) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, id)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockTasksRepositoryMockRecorder) GetTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockTasksRepository)(nil).GetTask), ctx, id)
}

// GetTasks mocks base method.
func (m *MockTasksRepository) GetTasks(ctx context.Context, filter tasks.GetTasksFilter) ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks", ctx, filter)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockTasksRepositoryMockRecorder) GetTasks(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockTasksRepository)(nil).GetTasks), ctx, filter)
}

// SaveTask mocks base method.
func (m *MockTasksRepository) SaveTask(ctx context.Context, task domain.Task) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTask", ctx, task)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveTask indicates an expected call of SaveTask.
func (mr *MockTasksRepositoryMockRecorder) SaveTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTask", reflect.TypeOf((*MockTasksRepository)(nil).SaveTask), ctx, task)
}

// UpdateTask mocks base method.
func (m *MockTasksRepository) UpdateTask(ctx context.Context, task domain.Task) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, task)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockTasksRepositoryMockRecorder) UpdateTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockTasksRepository)(nil).UpdateTask), ctx, task)
}

// MockTasksCache is a mock of TasksCache interface.
type MockTasksCache struct {
	ctrl     *gomock.Controller
	recorder *MockTasksCacheMockRecorder
	isgomock struct{}
}

// MockTasksCacheMockRecorder is the mock recorder for MockTasksCache.
type MockTasksCacheMockRecorder struct {
	mock *MockTasksCache
}

// NewMockTasksCache creates a new mock instance.
func NewMockTasksCache(ctrl *gomock.Controller) *MockTasksCache {
	mock := &MockTasksCache{ctrl: ctrl}
	mock.recorder = &MockTasksCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTasksCache) EXPECT() *MockTasksCacheMockRecorder {
	return m.recorder
}

// DeleteTask mocks base method.
func (m *MockTasksCache) DeleteTask(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTasksCacheMockRecorder) DeleteTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTasksCache)(nil).DeleteTask), ctx, id)
}

// GetTask mocks base method.
func (m *MockTasksCache) GetTask(ctx context.Context, id uuid.UUID) (domain.Task, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, id)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTask indicates an expected call of GetTask.
func (mr *MockTasksCacheMockRecorder) GetTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockTasksCache)(nil).GetTask), ctx, id)
}

// GetTasks mocks base method.
func (m *MockTasksCache) GetTasks(ctx context.Context, filter tasks.GetTasksFilter) ([]domain.Task, bool, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks", ctx, filter)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockTasksCacheMockRecorder) GetTasks(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockTasksCache)(nil).GetTasks), ctx, filter)
}

// InvalidateTasks mocks base method.
func (m *MockTasksCache) InvalidateTasks(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateTasks", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateTasks indicates an expected call of InvalidateTasks.
func (mr *MockTasksCacheMockRecorder) InvalidateTasks(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateTasks", reflect.TypeOf((*MockTasksCache)(nil).InvalidateTasks), ctx, userID)
}

// SetTask mocks base method.
func (m *MockTasksCache) SetTask(ctx context.Context, task domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTask indicates an expected call of SetTask.
func (mr *MockTasksCacheMockRecorder) SetTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTask", reflect.TypeOf((*MockTasksCache)(nil).SetTask), ctx, task)
}

// SetTasks mocks base method.
func (m *MockTasksCache) SetTasks(ctx context.Context, filter tasks.GetTasksFilter, version int64, arg3 []domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTasks", ctx, filter, version, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTasks indicates an expected call of SetTasks.
func (mr *MockTasksCacheMockRecorder) SetTasks(ctx, filter, version, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTasks", reflect.TypeOf((*MockTasksCache)(nil).SetTasks), ctx, filter, version, arg3)
}

// MockStatsCacheInvalidator is a mock of StatsCacheInvalidator interface.
type MockStatsCacheInvalidator struct {
	ctrl     *gomock.Controller
	recorder *MockStatsCacheInvalidatorMockRecorder
	isgomock struct{}
}

// MockStatsCacheInvalidatorMockRecorder is the mock recorder for MockStatsCacheInvalidator.
type MockStatsCacheInvalidatorMockRecorder struct {
	mock *MockStatsCacheInvalidator
}

// NewMockStatsCacheInvalidator creates a new mock instance.
func NewMockStatsCacheInvalidator(ctrl *gomock.Controller) *MockStatsCacheInvalidator {
	mock := &MockStatsCacheInvalidator{ctrl: ctrl}
	mock.recorder = &MockStatsCacheInvalidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsCacheInvalidator) EXPECT() *MockStatsCacheInvalidatorMockRecorder {
	return m.recorder
}

// InvalidateStats mocks base method.
func (m *MockStatsCacheInvalidator) InvalidateStats(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateStats", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateStats indicates an expected call of InvalidateStats.
func (mr *MockStatsCacheInvalidatorMockRecorder) InvalidateStats(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateStats", reflect.TypeOf((*MockStatsCacheInvalidator)(nil).InvalidateStats), ctx, userID)
}
