// Code generated by MockGen. DO NOT EDIT.
// Source: internal/features/stats/transport/http/transport.go
//
// Generated by this command:
//
//	mockgen -source=internal/features/stats/transport/http/transport.go -destination=internal/features/stats/transport/http/mocks/mock_transport.go -package=stats_transport_http_mocks
//

// Package stats_transport_http_mocks is a generated GoMock package.
package stats_transport_http_mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/horizoonn/todoapp/internal/core/domain"
	stats "github.com/horizoonn/todoapp/internal/features/stats"
	gomock "go.uber.org/mock/gomock"
)

// MockStatsService is a mock of StatsService interface.
type MockStatsService struct {
	ctrl     *gomock.Controller
	recorder *MockStatsServiceMockRecorder
	isgomock struct{}
}

// MockStatsServiceMockRecorder is the mock recorder for MockStatsService.
type MockStatsServiceMockRecorder struct {
	mock *MockStatsService
}

// NewMockStatsService creates a new mock instance.
func NewMockStatsService(ctrl *gomock.Controller) *MockStatsService {
	mock := &MockStatsService{ctrl: ctrl}
	mock.recorder = &MockStatsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsService) EXPECT() *MockStatsServiceMockRecorder {
	return m.recorder
}

// GetStats mocks base method.
func (m *MockStatsService) GetStats(ctx context.Context, filter stats.GetStatsFilter) (domain.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, filter)
	ret0, _ := ret[0].(domain.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockStatsServiceMockRecorder) GetStats(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockStatsService)(nil).GetStats), ctx, filter)
}
