// Code generated by MockGen. DO NOT EDIT.
// Source: internal/features/stats/service/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/features/stats/service/service.go -destination=internal/features/stats/service/mocks/mock_service.go -package=stats_service_mocks
//

// Package stats_service_mocks is a generated GoMock package.
package stats_service_mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/horizoonn/todoapp/internal/core/domain"
	stats "github.com/horizoonn/todoapp/internal/features/stats"
	gomock "go.uber.org/mock/gomock"
)

// MockStatsRepository is a mock of StatsRepository interface.
type MockStatsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStatsRepositoryMockRecorder
	isgomock struct{}
}

// MockStatsRepositoryMockRecorder is the mock recorder for MockStatsRepository.
type MockStatsRepositoryMockRecorder struct {
	mock *MockStatsRepository
}

// NewMockStatsRepository creates a new mock instance.
func NewMockStatsRepository(ctrl *gomock.Controller) *MockStatsRepository {
	mock := &MockStatsRepository{ctrl: ctrl}
	mock.recorder = &MockStatsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsRepository) EXPECT() *MockStatsRepositoryMockRecorder {
	return m.recorder
}

// GetStats mocks base method.
func (m *MockStatsRepository) GetStats(ctx context.Context, filter stats.GetStatsFilter) (domain.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, filter)
	ret0, _ := ret[0].(domain.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockStatsRepositoryMockRecorder) GetStats(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockStatsRepository)(nil).GetStats), ctx, filter)
}

// MockStatsCache is a mock of StatsCache interface.
type MockStatsCache struct {
	ctrl     *gomock.Controller
	recorder *MockStatsCacheMockRecorder
	isgomock struct{}
}

// MockStatsCacheMockRecorder is the mock recorder for MockStatsCache.
type MockStatsCacheMockRecorder struct {
	mock *MockStatsCache
}

// NewMockStatsCache creates a new mock instance.
func NewMockStatsCache(ctrl *gomock.Controller) *MockStatsCache {
	mock := &MockStatsCache{ctrl: ctrl}
	mock.recorder = &MockStatsCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsCache) EXPECT() *MockStatsCacheMockRecorder {
	return m.recorder
}

// GetStats mocks base method.
func (m *MockStatsCache) GetStats(ctx context.Context, filter stats.GetStatsFilter) (domain.Stats, bool, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, filter)
	ret0, _ := ret[0].(domain.Stats)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetStats indicates an expected call of GetStats.
func (mr *MockStatsCacheMockRecorder) GetStats(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockStatsCache)(nil).GetStats), ctx, filter)
}

// SetStats mocks base method.
func (m *MockStatsCache) SetStats(ctx context.Context, filter stats.GetStatsFilter, version int64, arg3 domain.Stats) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStats", ctx, filter, version, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStats indicates an expected call of SetStats.
func (mr *MockStatsCacheMockRecorder) SetStats(ctx, filter, version, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStats", reflect.TypeOf((*MockStatsCache)(nil).SetStats), ctx, filter, version, arg3)
}
