// Code generated by MockGen. DO NOT EDIT.
// Source: internal/features/tasks/transport/http/transport.go
//
// Generated by this command:
//
//	mockgen -source=internal/features/tasks/transport/http/transport.go -destination=internal/features/tasks/transport/http/mocks/mock_transport.go -package=tasks_transport_http_mocks
//

// Package tasks_transport_http_mocks is a generated GoMock package.
package tasks_transport_http_mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/horizoonn/todoapp/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTasksService is a mock of TasksService interface.
type MockTasksService struct {
	ctrl     *gomock.Controller
	recorder *MockTasksServiceMockRecorder
	isgomock struct{}
}

// MockTasksServiceMockRecorder is the mock recorder for MockTasksService.
type MockTasksServiceMockRecorder struct {
	mock *MockTasksService
}

// NewMockTasksService creates a new mock instance.
func NewMockTasksService(ctrl *gomock.Controller) *MockTasksService {
	mock := &MockTasksService{ctrl: ctrl}
	mock.recorder = &MockTasksServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTasksService) EXPECT() *MockTasksServiceMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTasksService) CreateTask(ctx context.Context, title string, description *string, authorUserID uuid.UUID) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, title, description, authorUserID)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTasksServiceMockRecorder) CreateTask(ctx, title, description, authorUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTasksService)(nil).CreateTask), ctx, title, description, authorUserID)
}

// DeleteTask mocks base method.
func (m *MockTasksService) DeleteTask(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTasksServiceMockRecorder) DeleteTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTasksService)(nil).DeleteTask), ctx, id)
}

// GetTask mocks base method.
func (m *MockTasksService) GetTask(ctx context.Context, id uuid.UUID) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, id)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockTasksServiceMockRecorder) GetTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockTasksService)(nil).GetTask), ctx, id)
}

// GetTasks mocks base method.
func (m *MockTasksService) GetTasks(ctx context.Context, userID *uuid.UUID, limit, offset *int) ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockTasksServiceMockRecorder) GetTasks(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockTasksService)(nil).GetTasks), ctx, userID, limit, offset)
}

// PatchTask mocks base method.
func (m *MockTasksService) PatchTask(ctx context.Context, id uuid.UUID, patch domain.TaskPatch) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchTask", ctx, id, patch)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchTask indicates an expected call of PatchTask.
func (mr *MockTasksServiceMockRecorder) PatchTask(ctx, id, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchTask", reflect.TypeOf((*MockTasksService)(nil).PatchTask), ctx, id, patch)
}
